// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var directionsDisplay, directionsSvc, getPlaces, getSearchParams, globalLatLng, infoWindow, initLatLng, initMap, map, placeIconDir, placeMarker, placesSvc;
    map = null;
    infoWindow = null;
    placesSvc = null;
    globalLatLng = null;
    placeIconDir = 'images/';
    directionsDisplay = null;
    directionsSvc = new google.maps.DirectionsService();
    initLatLng = function(position) {
      var lat, lng;
      lat = position.coords.latitude;
      lng = position.coords.longitude;
      $("#latLngContainer").text("" + lat + "-" + lng);
      return initMap(lat, lng, '', 0);
    };
    initMap = function(lat, lng, kw, radius) {
      var currentMarker, latLng, mapOptions, mapZoom, placesRequest;
      directionsDisplay = new google.maps.DirectionsRenderer({
        suppressMarkers: true
      });
      latLng = new google.maps.LatLng(lat, lng);
      mapZoom = 13;
      if ($("#latLngContainer").text()) {
        globalLatLng = latLng;
      }
      switch (radius) {
        case "500":
          mapZoom = 15;
          break;
        case "1000":
          mapZoom = 14;
          break;
        case "2000":
        case "3000":
          mapZoom = 13;
          break;
        case "4000":
        case "5000":
        case "6000":
          mapZoom = 12;
          break;
        case "7000":
        case "8000":
        case "9000":
        case "10000":
          mapZoom = 11;
      }
      mapOptions = {
        zoom: mapZoom,
        center: latLng,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
      directionsDisplay.setMap(map);
      currentMarker = new google.maps.Marker({
        map: map,
        position: latLng,
        animation: google.maps.Animation.DROP,
        icon: "" + placeIconDir + "curr_loc.png",
        draggable: true
      });
      placesRequest = {
        location: latLng,
        radius: radius,
        keyword: kw
      };
      placesSvc = new google.maps.places.PlacesService(map);
      infoWindow = new google.maps.InfoWindow();
      placesSvc.nearbySearch(placesRequest, getPlaces);
      return google.maps.event.addListener(currentMarker, 'dragend', function(e) {
        lat = e.latLng.lat();
        lng = e.latLng.lng();
        globalLatLng = new google.maps.LatLng(lat, lng);
        return $("#latLngContainer").text("" + lat + "-" + lng);
      });
    };
    getPlaces = function(results, status) {
      var detailReq, drawCircle, drawRadius, i, pImage, pMoreInfo, pPhone, pS, pWeb;
      pS = placesSvc;
      pPhone = 'N/A';
      pWeb = 'N/A';
      pImage = "" + placeIconDir + "default_place_img.jpg";
      pMoreInfo = '';
      $("#resultList").html('');
      drawRadius = parseInt($("#radius").val());
      drawCircle = new google.maps.Circle({
        map: map,
        center: globalLatLng,
        radius: drawRadius,
        strokeColor: '#FF0000',
        strokeOpacity: 0.8,
        strokeWeight: 1,
        fillColor: '#FF0000',
        fillOpacity: 0.35
      });
      if (status === google.maps.places.PlacesServiceStatus.OK) {
        i = 0;
        while (i < results.length) {
          placeMarker(results[i]);
          detailReq = {
            reference: results[i].reference
          };
          pS.getDetails(detailReq, function(details, s) {
            if (details.formatted_phone_number) {
              pPhone = details.formatted_phone_number;
            }
            if (details.website) {
              pWeb = "<a href='" + details.website + "' target='_blank'>" + details.name + "</a>";
            }
            if (details.photos) {
              pImage = details.photos[0].getUrl({
                'maxWidth': 88,
                'maxHeight': 88
              });
            }
            if (details.url) {
              pMoreInfo = "<a href='" + details.url + "' target='_blank'>More info</a>";
            }
          });
          i++;
        }
      } else {
        alert('Cannot find places');
      }
      google.maps.event.addListener(map, 'click', function() {
        infoWindow.close();
      });
    };
    placeMarker = function(places) {
      var detailReq, marker, pImage, pMoreInfo, pPhone, pWeb, placeLoc;
      placeLoc = places.geometry.location;
      detailReq = {
        reference: places.reference
      };
      pPhone = 'N/A';
      pWeb = 'N/A';
      pImage = "" + placeIconDir + "default_place_img";
      pMoreInfo = '';
      marker = new google.maps.Marker({
        map: map,
        position: placeLoc,
        animation: google.maps.Animation.DROP
      });
      google.maps.event.addListener(marker, 'click', function(e) {
        var req;
        req = {
          origin: globalLatLng,
          destination: e.latLng,
          travelMode: google.maps.DirectionsTravelMode.DRIVING
        };
        if ($("#direction").is(":checked")) {
          directionsSvc.route(req, function(r, s) {
            if (s === google.maps.DirectionsStatus.OK) {
              directionsDisplay.setDirections(r);
            } else {
              alert('err');
            }
          });
        }
      });
      google.maps.event.addListener(marker, 'click', function() {
        placesSvc.getDetails(detailReq, function(details, status) {
          if (details.formatted_phone_number) {
            pPhone = details.formatted_phone_number;
          }
          if (details.website) {
            pWeb = "<a href='" + details.website + "' target='_blank'>" + details.name + "</a>";
          }
          if (details.photos) {
            pImage = details.photos[0].getUrl({
              'maxWidth': 88,
              'maxHeight': 88
            });
          }
          if (details.url) {
            pMoreInfo = "<a href='" + details.url + "' target='_blank'>More info</a>";
          }
          infoWindow.setContent("<img src='" + pImage + "' style='margin-right: 10px; float: left; border: 1px solid #CCC;' alt='http://namnv609.cf' /><b>" + details.name + "</b> - " + pMoreInfo + "<br /><br />- Địa chỉ: " + details.formatted_address + "<br />- Điện thoại: " + pPhone + "<br />- Website: " + pWeb);
        });
        infoWindow.open(map, this);
      });
    };
    getSearchParams = function() {
      var $latLngContainer, kw, lat, lng, radius;
      $latLngContainer = $("#latLngContainer");
      lat = $latLngContainer.text().split('-')[0];
      lng = $latLngContainer.text().split('-')[1];
      kw = $("#keyword").val().trim();
      radius = $("#radius").val();
      if (kw !== null && kw !== '') {
        initMap(lat, lng, kw, radius);
      } else if (lat === '' || (lat == null) || lat === undefined || lng === '' || (lng == null) || lng === 'undefined') {
        alert('Cannot get current location. Plz try again later');
      } else {
        $("#keyword").focus();
      }
    };
    $("#keyword").on("keypress", function(e) {
      if (e.keyCode === 13) {
        return getSearchParams();
      }
    });
    $("#radius").on("change", function() {
      return getSearchParams();
    });
    $("#search").on("click", function() {
      return getSearchParams();
    });
    if (navigator.geolocation) {
      return navigator.geolocation.getCurrentPosition(initLatLng);
    } else {
      return alert('Your browser does not support Geolocation. Please upgrade your browser to latest version.');
    }
  });

}).call(this);
